INSERT INTO jogos(nome, dataDeLancamento, genero, descricao, classificacao, valor, fornecedor, caminhoImagem, caminhoTrailer) VALUES 
("Grand Theft Auto V",
 "2015-04-14",
 "Mundo aberto",
 "Quando um malandro de rua, um ladrão de bancos aposentado e um psicopata aterrorizante se envolvem com alguns dos criminosos mais assustadores e loucos do submundo, o governo dos EUA e a indústria do entretenimento, eles devem realizar golpes ousados para sobreviver nessa cidade implacável onde não podem confiar em ninguém, nem mesmo um no outro.",
 18,
 69.99,
 "Rockstar North",
 "Imagens/gtav2.jpg",
 "hvoD7ehZPcM"),

("Tom Clancys Rainbow Six Siege",
 "2015-12-1",
 "Jogo de tiro tático",
 "Domine a arte da destruição e do uso de gadgets em Tom Clancy’s Rainbow Six Siege. Enfrente combates intensos em curta distância, alta letalidade, decisões táticas, jogabilidade em equipe e ação explosiva a todo momento. Vivencie uma nova era de tiroteios ferozes e estratégia de alto nível nascida do grande legado dos jogos de Tom Clancy's Rainbow Six passados.",
 18,
 59.99,
 "Ubisoft Montreal",
 "Imagens/r6.jpg",
 "KlbLLRdg9u8"),

("Resident Evil 2: Remake",
 "2019-01-25",
 "Survival horror",
 "Em Resident Evil 2, a ação clássica, exploração tensa e a jogabilidade de resolver quebra-cabeças que definiu a série Resident Evil retorna. Os jogadores se juntam ao policial novato, Leon S. Kennedy, e à estudante universitária, Claire Redfield, que acabam juntos por uma epidemia desastrosa em Raccoon City que transformou sua população em zumbis mortais. Leon e Claire possuem suas próprias campanhas separadas, permitindo que os jogadores vejam a história da perspectiva de ambos os personagens. O destino desses dois personagens favoritos dos fãs está nas mãos dos jogadores conforme eles trabalham juntos para sobreviver e descobrir o que está por trás do terrível ataque à cidade. Será que eles sairão com vida?",
 "16",
 129.99,
 "CAPCOM Co.",
 "Imagens/re2.jpg",
 "VyymfKuMEXI"),
 
 ("Injustice: Gods Among Us",
 "2013-11-12",
 "Luta",
 "Injustice: Gods Among Us Ultimate Edition aprimora o novo e ousado jogo de luta da NetherRealm Studios. Com seis personagens novos, mais de 30 skins atuais e 60 missões inéditas dos Laboratórios S.T.A.R., esta edição vai causar impacto. Além dos ícones da DC Comics como Batman, Coringa, Lanterna Verde, Flash, Superman e Mulher-Maravilha, o novo jogo do estúdio premiado tem uma história profunda e original. Heróis e vilões vão travar batalhas épicas em um mundo onde o limite entre o bem e o mal é tênue.",
 "16",
 49.99,
 "NetherRealm Studios",
 "Imagens/injustice.jpg",
 "hMkTQSbE6Bc"),
 
 ("Hunt: Showdown",
 "2019-08-27",
 "Ação",
 "Monstros cruéis e sinistros vagueiam pelos pântanos do Louisiana, e tu fazes parte de um grupo de duros pistoleiros destinados a livrar o mundo da sua temível presença. Purga estas criaturas do nosso mundo e serás pago generosamente, tendo a oportunidade de comprar armas mais terríveis e poderosas. Falha, e a morte vai tirar-te tanto o teu equipamento como a tua personagem. No entanto, a tua experiência permanecerá sempre no teu conjunto de Hunters (Caçadores), chamado Bloodline (Linhagem).",
 "16",
 89.99,
 "Crytek",
 "Imagens/hunt.jpg",
 "lO4-ZV7oDgU"),

("PLAYERUNKNOWNS BATTLEGROUNDS",
 "2017-12-21",
 "Ação",
 "PLAYERUNKNOWN'S BATTLEGROUNDS é um shooter de battle royale que coloca 100 jogadores um contra o outro em uma luta pela sobrevivência. Reúna suprimentos e engane seus oponentes para se tornar a última pessoa viva.",
 "16",
 55.99,
 "PUBG Corporation",
 "Imagens/pub.jpg",
 "6TctZbvFU5Y"),

("Cyberpunk 2077",
 "2019-04-15",
 "RPG",
 "Cyberpunk 2077 é uma história de ação e aventura de mundo aberto ambientada em Night City, uma megalópole obcecada por poder, glamour e biomodificações. Você joga como V, um mercenário fora da lei atrás de um implante único que carrega a chave da imortalidade. Você pode personalizar aparatos cibernéticos, conjunto de habilidades e estilo de jogo do personagem e explorar uma vasta cidade onde as decisões tomadas definem a história e o mundo ao seu redor.",
 "18",
 199.99,
 "CD PROJEKT RED",
 "Imagens/cb2077.jpg",
 "NgEg2zW3l38"),
 
("The Witcher 3: Wild Hunt",
 "2015-05-18",
 "RPG",
 "The Witcher: Wild Hunt é um RPG de mundo aberto de fantasia cheio de escolhas vitais. Em The Witcher, você joga como um caçador de monstros profissional, Geralt de Rívia, em busca da criança da profecia em um vasto mundo aberto, rico em cidades mercantis, ilhas piratas, passagens perigosas nas montanhas e cavernas esquecidas a serem exploradas.",
 "18",
 79.99,
 "CD PROJEKT RED",
 "Imagens/thewitcher2.jpg",
 "xt_65k-gv1U"),
 
("Minecraftt",
 "2009-05-17",
 "Sandbox",
 "Minecraft é um jogo basicamente feito de blocos, tendo as paisagens e a maioria de seus objetos compostos por eles, e permitindo que estes sejam removidos e recolocados em outros lugares para criar construções, empilhando-os. Além da mecânica de mineração e coleta de recursos para construção, há no jogo mistura de sobrevivência, e exploração. Jogar Minecraft é usá-lo como ferramenta criativa. Não há forma de vencer em Minecraft, uma vez que não há objetivos requeridos e enredo dramático que necessite ser seguido. Os jogadores passam a maior parte de seu tempo simplesmente minerando e construindo blocos de material virtual, daí o nome do jogo. Uma vez que os jogadores tenham coletado e construído um inventário suficiente de recursos e alguns minérios, eles usam estas aquisições virtuais para conceber casas e paisagens, muitas vezes construindo todos os tipos de estruturas de blocos. ",
 "L",
 25.99,
 "Mojang",
 "Imagens/mine.jpg",
 "MmB9b5njVbA"),
 
 ("Dying Light 2",
 "2019-08-22",
 "Ação",
 "Já se passaram 15 anos desde que a humanidade foi derrotada pelo vírus. O último grande povoado da humanidade existe dentro de um mundo infectado e implacável que foi lançado em uma idade das trevas moderna. Durante o dia, bandidos, facções e sobreviventes famintos vagam pelas ruas em busca de migalhas ou de alguém que as tenha e não seja forte o suficiente para se defender. Os infectados tomam conta das ruas à noite. Saem de seus refúgios sombrios e caçam os vivos. Controle o sobrevivente infectado Aiden Caldwell. A sua agilidade ímpar e as suas habilidades de combate fazem de você um aliado poderoso e um bem precioso neste mundo inóspito. Você faz coisas que ninguém mais conseguiria. Entra em lugares que ninguém mais ousaria. Com as suas habilidades únicas você tem o poder de ser o agente da mudança dentro desta metrópole decadente.",
 "18",
 179.99,
 "Techland",
 "Imagens/dl2.jpg",
 "6tPU813CMtI"),

 ("Call of Duty: Modern Warfare",
 "2019-08-25",
 "FPS",
 "As apostas nunca foram tão altas, agora que os jogadores assumem o papel de operadores letais de alto nível em uma saga que vai afetar o equilíbrio global de poder. Desenvolvido pelo estúdio que começou tudo, Infinity Ward oferece uma releitura épica da icônica série Modern Warfare® a partir do zero.",
 "18",
 199.99,
 "Infinity Ward",
 "Imagens/codmw.jpg",
 "bH1lHCirCGI"),
 
("Counter-Strike: Global Offensive",
 "2012-08-21",
 "FPS",
 "Counter-Strike: Global Offensive (CS: GO) expandirá na jogabilidade de ação baseada em equipes na qual foi pioneiro quando foi lançado há 12 anos. CS: GO contém novos mapas, personagens e armas, além de conter versões atualizadas de conteúdos do CS clássico (como de_dust2). Além disso, CS: GO introduzirá novos modos de jogo, criação de partidas (matchmaking), placares de líderes e mais. Pelos últimos 12 anos, ele continuou sendo um dos jogos mais jogados no mundo, manteve destaque em torneios competitivos de jogos e a franquia vendeu mais de 26 milhões de cópias no mundo todo.",
 "16",
 55.99,
 "Valve",
 "Imagens/csgo.jpg",
 "edYCtaNueQY");
 
INSERT INTO formaDePagamento VALUES (1,"Credito"), (2, "Debito"), (3, "Boleto");